//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class MyStringLengthAttribute : StringLengthAttribute
    {
        public MyStringLengthAttribute(int maximumLength)
            : base(maximumLength)
        {
        }

        public override bool IsValid(object value)
        {
            string val = Convert.ToString(value);
            if (val.Length < base.MinimumLength)
                base.ErrorMessage = "*minimum length should be 3";
            if (val.Length > base.MaximumLength)
                base.ErrorMessage = "*maximum length should be 50";
            return base.IsValid(value);
        }
    }


    public partial class Employee
    {
        [Key]
        public int Id { get; set; }

        [Display(Name ="First Name")]
        [MyStringLength(50, MinimumLength = 3)]
        [Required(ErrorMessage ="*first name required")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [MyStringLength(50, MinimumLength = 3)]
        [Required(ErrorMessage = "*last name required")]
        public string LastName { get; set; }

        [Display(Name = "Designation")]
        [Required(ErrorMessage = "*designation required")]
        public string Designation { get; set; }

        [Display(Name = "Employee Salary")]
        [Required(ErrorMessage = "*salary required")]
        public Nullable<int> Salary { get; set; }

        [Display(Name = "Department Name")]
        [Required(ErrorMessage = "*department name required")]
        public Nullable<int> DepartmentCode { get; set; }

        [Display(Name = "Date of Joining")]
        [DataType(DataType.DateTime)]
        [Required(ErrorMessage = "*Date of joining must be a date")]
        //public DateTime DateOfJoining { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }

        [Display(Name = "Office Location")]
        [Required(ErrorMessage = "*office location required")]
        public string OfficeLocation { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
